version: "3.7"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: "America/Sao_Paulo"
      TZ: "America/Sao_Paulo"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      DB_TYPE: "postgresdb"
      DB_POSTGRESDB_DATABASE: "<POSTGRES_DATABASE>"
      DB_POSTGRESDB_HOST: "<POSTGRES_HOST>"
      DB_POSTGRESDB_PORT: "<POSTGRES_PORT>"
      DB_POSTGRESDB_USER: "<POSTGRES_USER>"
      DB_POSTGRESDB_SCHEMA: "<POSTGRES_SCHEMA>"
      DB_POSTGRESDB_PASSWORD: "<POSTGRES_PASSWORD>"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
    driver: local