apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-connect
  namespace: kafka-connect
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - kafka.<valid_domain>
      secretName: kafka-connect-tls
  rules:
    - host: kafka.<valid_domain>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-connect
                port:
                  number: 8083